from rest_framework import serializers
from .models import PaperRank

class PaperRankSerializer(serializers.ModelSerializer):
    class Meta:
        model = PaperRank
        fields = [
        'Authors', 
        'Authors_full_names', 
        'Author_ID', 
        'Title', 
        'Year', 
        'Source_title', 
        'Volume', 
        'Issue', 
        'Art_No', 
        'Page_start', 
        'Page_end',
        'Page_count', 
        'Citations', 
        'DOI', 
        'Link',
        'Affiliations',
        'Authors_with_Affiliations',
        'Abstract',
        'Author_Keywords',
        'Index_Keywords',
        'Molecular_Sequence_Numbers',
        'Chemicals',
        'Tradenames',
        'Manufacturers',
        'Funding_Details',
        'Funding_Texts',
        'Reference',
        'Correspondence_Address',
        'Editors',
        'Publisher',
        'Sponsors',
        'Conference_name',
        'Conference_date',
        'Conference_location',
        'Conference_code',
        'ISSN',
        'ISBN',
        'CODEN',
        'PubMed_ID',
        'Language', 
        'Abbreviated_Source_Title',
        'Document', 
        'Publication_Stage',
        'Open_Access',
        'Source',
        
        ]
